### PR TITLE
[LOOP-3490] Add Health Store permissions to Tidepool Onboarding

### PR DESCRIPTION
**Pull request by darinkrauss**
- https://tidepool.atlassian.net/browse/LOOP-3490
- Add health store authorization view

### CODE REVIEW

**Comment by darinkrauss** [comment]
LW PR for build: https://github.com/tidepool-org/LoopWorkspace/pull/561

**Review by nhamming — APPROVED** [review]
LGTM

**Comment by darinkrauss** [comment]
@nhamming I added a couple of changes to fix an issue with the navigation views being abruptly changed. Would you mind reviewing this last commit, too? Thanks!

**Review by nhamming — APPROVED** [review]
LGTM

**Pull request merged**
