### PR TITLE
[LOOP-3112] Onboarding therapy setting uses pump supported increments

### PR DESCRIPTION
**Pull request by darinkrauss**
- https://tidepool.atlassian.net/browse/LOOP-3112
- Add pump manager type-based supported increments for onboarding
- Add CGM and pump manager type-based image for onboarding
- Remove unnecessary images

### CODE REVIEW

**Review by nhamming — APPROVED** [review]
LGTM

**Comment by darinkrauss** [comment]
LW PR for build: https://github.com/tidepool-org/LoopWorkspace/pull/533

**Review by rickpasetto — APPROVED** [review]
LGTM

**Review by ps2 — APPROVED** [review]
LGTM!

**Pull request merged**
